services:
  movensys_vlm:
    build:
      context: ..
      dockerfile: docker/movensys_vlm.Dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO}
    image: movensys_vlm_image:latest
    container_name: movensys_vlm_container
    volumes:
      - ${MOVENSYS_MANIPULATOR_PACKAGES}:/app/movensys_ws/src/movensys-manipulator:ro
      - movensys_ws_build:/app/movensys_ws/build
      - movensys_ws_install:/app/movensys_ws/install
    restart: unless-stopped
    network_mode: host
    environment:
      ROS_DISTRO: ${ROS_DISTRO}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      MOVENSYS_MANIPULATOR_PACKAGES: ${MOVENSYS_MANIPULATOR_PACKAGES}
      VLLM_BASE_URL: ${VLLM_BASE_URL}
      VLM_MODEL_NAME: ${VLM_MODEL_NAME}

volumes:
  movensys_ws_build:
  movensys_ws_install:
